Iss33
tanmayc07/Blog-App pull request #36
Opened 2020-09-22 11:23 UTC by sahilambre

Issue #33  Update documentation

2020-09-22 13:24 UTC, tanmayc07 requested changes

2020-09-22 13:26 UTC, sahilambre commented on README.md
>  # A Blogging website built with Nodejs
Ok, even I was thinking of the same.

2020-09-22 13:26 UTC, sahilambre commented on README.md
> +4. To **start** the server run
ok

2020-09-22 13:29 UTC, sahilambre commented
Changes have been made. Please check @tanmayc07

2020-09-22 13:36 UTC, tanmayc07 commented
I think we should add the header content as body after header, and write a new header. Something like Think it Write it!

2020-09-22 13:47 UTC, sahilambre commented
> 
> 
> I think we should add the header content as body after header, and write a new header. Something like Think it. Write it!

Something like this??
![image](https://user-images.githubusercontent.com/59484827/93890635-3214a180-fd08-11ea-8d17-cfa560011706.png)

2020-09-22 13:48 UTC, tanmayc07 commented
No I meant just change the text in header as `Think it. Write it!` 
And below that write in that previous header text as normal text.

2020-09-23 16:44 UTC, tanmayc07 commented
@sahilambre Are you working on this?

2020-09-24 05:26 UTC, sahilambre commented
Yes

2020-09-24 08:22 UTC, tanmayc07 requested changes

2020-09-24 08:22 UTC, tanmayc07 commented on README.md
> +## **How to run code locally**
Change it to `###` . It still looks equal as h1

2020-10-19 13:22 UTC, tanmayc07 approved these changes

2020-10-19 13:23 UTC, merged